{% set name = "powerfit" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1e7d86a2046b133294cae020ea2f4038db18d3f546b080141835cd969847b215

build:
  number: 1
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - scipy
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - powerfit
  commands:
    - pip check
    - python -c "import powerfit; assert powerfit.version == '{{ version }}'"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tdegeus/powerfit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple fit of a power-law to data
  description: Simple fit of a power-law to data
  doc_url: https://powerfit.readthedocs.io
  dev_url: https://github.com/tdegeus/powerfit

extra:
  recipe-maintainers:
    - tdegeus
